// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl-y7dBtO0CWfiy0FGEmEUXShbRYLi-HU',
    appId: '1:838525352984:web:6bc9c347ebdd2d235f176d',
    messagingSenderId: '838525352984',
    projectId: 'flutterproject-414b8',
    authDomain: 'flutterproject-414b8.firebaseapp.com',
    storageBucket: 'flutterproject-414b8.appspot.com',
    measurementId: 'G-350N3TRZ5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOVsipUfmc6mHnixHPyRfDoZ1PUAnrBFg',
    appId: '1:838525352984:android:0da54ffdb905f5285f176d',
    messagingSenderId: '838525352984',
    projectId: 'flutterproject-414b8',
    storageBucket: 'flutterproject-414b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbXU3_hNYDtzDFxcNyu0ubEVuzb8Is2YM',
    appId: '1:838525352984:ios:03119909db999e275f176d',
    messagingSenderId: '838525352984',
    projectId: 'flutterproject-414b8',
    storageBucket: 'flutterproject-414b8.appspot.com',
    iosBundleId: 'com.example.demoFlutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbXU3_hNYDtzDFxcNyu0ubEVuzb8Is2YM',
    appId: '1:838525352984:ios:03119909db999e275f176d',
    messagingSenderId: '838525352984',
    projectId: 'flutterproject-414b8',
    storageBucket: 'flutterproject-414b8.appspot.com',
    iosBundleId: 'com.example.demoFlutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl-y7dBtO0CWfiy0FGEmEUXShbRYLi-HU',
    appId: '1:838525352984:web:40ab69afa36b6a125f176d',
    messagingSenderId: '838525352984',
    projectId: 'flutterproject-414b8',
    authDomain: 'flutterproject-414b8.firebaseapp.com',
    storageBucket: 'flutterproject-414b8.appspot.com',
    measurementId: 'G-T1MGQ65NK8',
  );

}